// <auto-generated />
using System;
using HZ.IDTS.DigitalTwin.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HZ.IDTS.DigitalTwin.Infrastructure.Migrations
{
    [DbContext(typeof(DigitalTwinDbContext))]
    [Migration("20260709080033_InitDigitalTwinSchema")]
    partial class InitDigitalTwinSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.AssetManifest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_version_id");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("manifest_json")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.Property<string>("ModelStatsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("model_stats_json");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AssetVersionId")
                        .IsUnique();

                    b.HasIndex("ModelAssetId");

                    b.ToTable("asset_manifest", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ArchivedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_time");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.Property<DateTime?>("PublishedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_time");

                    b.Property<int>("VersionNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version_no");

                    b.Property<string>("VersionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("version_status");

                    b.HasKey("Id");

                    b.HasIndex("VersionStatus");

                    b.HasIndex("ModelAssetId", "VersionNo")
                        .IsUnique();

                    b.ToTable("asset_version", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_code");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_name");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<decimal>("PositionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("position_x");

                    b.Property<decimal>("PositionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("position_y");

                    b.Property<decimal>("PositionZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("position_z");

                    b.Property<decimal>("RotationX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rotation_x");

                    b.Property<decimal>("RotationY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rotation_y");

                    b.Property<decimal>("RotationZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rotation_z");

                    b.Property<decimal>("ScaleX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("scale_x");

                    b.Property<decimal>("ScaleY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("scale_y");

                    b.Property<decimal>("ScaleZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("scale_z");

                    b.Property<long>("SceneNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("scene_node_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("DeviceName");

                    b.HasIndex("Enabled");

                    b.HasIndex("SceneNodeId");

                    b.ToTable("device_instance", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceModelBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActiveFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_from")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ActiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_to");

                    b.Property<long>("AssetVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_version_id");

                    b.Property<string>("BindingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("binding_status");

                    b.Property<long>("DeviceInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_instance_id");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetVersionId");

                    b.HasIndex("BindingStatus");

                    b.HasIndex("DeviceInstanceId")
                        .IsUnique()
                        .HasFilter("binding_status = 'active'");

                    b.HasIndex("ModelAssetId");

                    b.HasIndex("DeviceInstanceId", "AssetVersionId")
                        .IsUnique();

                    b.ToTable("device_model_binding", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("asset_name");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("device_glb")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version_id");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("processing_status");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_file_hash");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_file_name");

                    b.Property<string>("SourceFileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("glb")
                        .HasColumnName("source_file_type");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("AssetCode")
                        .IsUnique();

                    b.HasIndex("AssetName");

                    b.HasIndex("AssetType");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("SourceFileHash")
                        .IsUnique();

                    b.ToTable("model_asset", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAssetVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_version_id");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("file_size");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<int?>("MaterialCount")
                        .HasColumnType("integer")
                        .HasColumnName("material_count");

                    b.Property<int?>("MeshCount")
                        .HasColumnType("integer")
                        .HasColumnName("mesh_count");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.Property<int?>("TextureCount")
                        .HasColumnType("integer")
                        .HasColumnName("texture_count");

                    b.Property<long?>("TriangleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("triangle_count");

                    b.Property<string>("VariantLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("source")
                        .HasColumnName("variant_level");

                    b.Property<long?>("VertexCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vertex_count");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.HasIndex("ModelAssetId");

                    b.HasIndex("VariantLevel");

                    b.HasIndex("AssetVersionId", "VariantLevel")
                        .IsUnique();

                    b.ToTable("model_asset_variant", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelConversionJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_version_id");

                    b.Property<long?>("ElapsedMs")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_ms");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<DateTime?>("FinishedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_time");

                    b.Property<string>("InputFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("input_file");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("upload")
                        .HasColumnName("job_type");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.Property<string>("OutputDirectory")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("output_directory");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("StderrLogUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stderr_log_url");

                    b.Property<string>("StdoutLogUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stdout_log_url");

                    b.HasKey("Id");

                    b.HasIndex("AssetVersionId");

                    b.HasIndex("JobType");

                    b.HasIndex("ModelAssetId");

                    b.HasIndex("Status");

                    b.ToTable("model_conversion_job", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelObjectIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_version_id");

                    b.Property<decimal?>("BoundingBoxMaxX")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bounding_box_max_x");

                    b.Property<decimal?>("BoundingBoxMaxY")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bounding_box_max_y");

                    b.Property<decimal?>("BoundingBoxMaxZ")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bounding_box_max_z");

                    b.Property<decimal?>("BoundingBoxMinX")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bounding_box_min_x");

                    b.Property<decimal?>("BoundingBoxMinY")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bounding_box_min_y");

                    b.Property<decimal?>("BoundingBoxMinZ")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("bounding_box_min_z");

                    b.Property<string>("MeshFingerprint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("mesh_fingerprint");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("object_name");

                    b.Property<string>("ObjectPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("object_path");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("object_type");

                    b.Property<string>("ObjectUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("object_uuid");

                    b.Property<string>("ParentPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("parent_path");

                    b.Property<string>("ParentUuid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_uuid");

                    b.HasKey("Id");

                    b.HasIndex("MeshFingerprint");

                    b.HasIndex("ModelAssetId");

                    b.HasIndex("ObjectName");

                    b.HasIndex("ObjectPath");

                    b.HasIndex("ObjectUuid");

                    b.HasIndex("AssetVersionId", "ObjectPath");

                    b.HasIndex("AssetVersionId", "ObjectUuid");

                    b.ToTable("model_object_index", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.MotionTarget", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<long>("MovablePartId")
                        .HasColumnType("bigint")
                        .HasColumnName("movable_part_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.Property<string>("TargetCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_code");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_name");

                    b.Property<decimal?>("TargetValue")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_value");

                    b.Property<decimal?>("TargetX")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_x");

                    b.Property<decimal?>("TargetY")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_y");

                    b.Property<decimal?>("TargetZ")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("target_z");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("TargetValue");

                    b.HasIndex("MovablePartId", "TargetCode")
                        .IsUnique();

                    b.ToTable("motion_target", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.MovablePartBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AssetVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("asset_version_id");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("z")
                        .HasColumnName("axis");

                    b.Property<string>("AxisMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("world")
                        .HasColumnName("axis_mode");

                    b.Property<string>("BindingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("binding_status");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("business_name");

                    b.Property<decimal>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("current_value");

                    b.Property<decimal?>("CustomAxisX")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("custom_axis_x");

                    b.Property<decimal?>("CustomAxisY")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("custom_axis_y");

                    b.Property<decimal?>("CustomAxisZ")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("custom_axis_z");

                    b.Property<decimal>("DefaultSpeed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(1m)
                        .HasColumnName("default_speed");

                    b.Property<long?>("DeviceInstanceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_instance_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<decimal>("HomeValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("home_value");

                    b.Property<decimal>("MaxValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("max_value");

                    b.Property<decimal>("MinValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_value");

                    b.Property<long>("ModelAssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("model_asset_id");

                    b.Property<string>("MotionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("linear")
                        .HasColumnName("motion_type");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("object_name");

                    b.Property<string>("ObjectPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("object_path");

                    b.Property<string>("ObjectUuid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("object_uuid");

                    b.Property<string>("ParentPath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("parent_path");

                    b.Property<string>("ParentUuid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_uuid");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_code");

                    b.HasKey("Id");

                    b.HasIndex("BindingStatus");

                    b.HasIndex("BusinessName");

                    b.HasIndex("DeviceInstanceId");

                    b.HasIndex("Enabled");

                    b.HasIndex("ModelAssetId");

                    b.HasIndex("ObjectPath");

                    b.HasIndex("ObjectUuid");

                    b.HasIndex("AssetVersionId", "PartCode")
                        .IsUnique();

                    b.ToTable("movable_part_binding", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.OperationAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation_type");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operator_name");

                    b.Property<long>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTime");

                    b.HasIndex("OperationType");

                    b.HasIndex("TargetId");

                    b.HasIndex("TargetType");

                    b.ToTable("operation_audit", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.SceneNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("NodeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_code");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("node_name");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("scene")
                        .HasColumnName("node_type");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_no");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("NodeCode")
                        .IsUnique();

                    b.HasIndex("NodeName");

                    b.HasIndex("NodeType");

                    b.HasIndex("ParentId");

                    b.ToTable("scene_node", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ToolHealthCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("unknown")
                        .HasColumnName("status");

                    b.Property<long>("ToolPackageId")
                        .HasColumnType("bigint")
                        .HasColumnName("tool_package_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckedTime");

                    b.HasIndex("Status");

                    b.HasIndex("ToolPackageId", "CheckedTime");

                    b.ToTable("tool_health_check", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ToolPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("InstallPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("install_path");

                    b.Property<string>("ToolCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tool_code");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_name");

                    b.Property<DateTime>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_time")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.HasIndex("ToolCode")
                        .IsUnique();

                    b.HasIndex("Version");

                    b.ToTable("tool_package", (string)null);
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.AssetManifest", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "AssetVersion")
                        .WithOne("Manifest")
                        .HasForeignKey("HZ.IDTS.DigitalTwin.Domain.Entities.AssetManifest", "AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("Manifests")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetVersion");

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("Versions")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceInstance", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.SceneNode", "SceneNode")
                        .WithMany("DeviceInstances")
                        .HasForeignKey("SceneNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SceneNode");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceModelBinding", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "AssetVersion")
                        .WithMany("DeviceModelBindings")
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceInstance", "DeviceInstance")
                        .WithMany("DeviceModelBindings")
                        .HasForeignKey("DeviceInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("DeviceModelBindings")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetVersion");

                    b.Navigation("DeviceInstance");

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "CurrentVersion")
                        .WithMany("CurrentForAssets")
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAssetVariant", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "AssetVersion")
                        .WithMany("Variants")
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("Variants")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetVersion");

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelConversionJob", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "AssetVersion")
                        .WithMany("ConversionJobs")
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("ConversionJobs")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetVersion");

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelObjectIndex", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "AssetVersion")
                        .WithMany("ObjectIndexes")
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("ObjectIndexes")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetVersion");

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.MotionTarget", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.MovablePartBinding", "MovablePart")
                        .WithMany("MotionTargets")
                        .HasForeignKey("MovablePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MovablePart");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.MovablePartBinding", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", "AssetVersion")
                        .WithMany("MovablePartBindings")
                        .HasForeignKey("AssetVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceInstance", "DeviceInstance")
                        .WithMany("MovablePartBindings")
                        .HasForeignKey("DeviceInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", "ModelAsset")
                        .WithMany("MovablePartBindings")
                        .HasForeignKey("ModelAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetVersion");

                    b.Navigation("DeviceInstance");

                    b.Navigation("ModelAsset");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.SceneNode", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.SceneNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ToolHealthCheck", b =>
                {
                    b.HasOne("HZ.IDTS.DigitalTwin.Domain.Entities.ToolPackage", "ToolPackage")
                        .WithMany("HealthChecks")
                        .HasForeignKey("ToolPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ToolPackage");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.AssetVersion", b =>
                {
                    b.Navigation("ConversionJobs");

                    b.Navigation("CurrentForAssets");

                    b.Navigation("DeviceModelBindings");

                    b.Navigation("Manifest");

                    b.Navigation("MovablePartBindings");

                    b.Navigation("ObjectIndexes");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.DeviceInstance", b =>
                {
                    b.Navigation("DeviceModelBindings");

                    b.Navigation("MovablePartBindings");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ModelAsset", b =>
                {
                    b.Navigation("ConversionJobs");

                    b.Navigation("DeviceModelBindings");

                    b.Navigation("Manifests");

                    b.Navigation("MovablePartBindings");

                    b.Navigation("ObjectIndexes");

                    b.Navigation("Variants");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.MovablePartBinding", b =>
                {
                    b.Navigation("MotionTargets");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.SceneNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DeviceInstances");
                });

            modelBuilder.Entity("HZ.IDTS.DigitalTwin.Domain.Entities.ToolPackage", b =>
                {
                    b.Navigation("HealthChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
